import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/providers/auth-provider';
import { Suspense } from 'react';
import { Toaster } from '@/components/ui/sonner';
import ReactQueryProvider from '@/providers/tanstack-provider';
import ToolTipProvider from '@/providers/tooltip-provider';
import ModalTaskProvider from '@/providers/modal-task-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Multi-User Project Management App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} dark antialiased`}>
        <ToolTipProvider>
          <ReactQueryProvider>
            <Suspense>
              <AuthProvider>
                {children}
                <Toaster position="top-center" richColors />
                <ModalTaskProvider />
              </AuthProvider>
            </Suspense>
          </ReactQueryProvider>
        </ToolTipProvider>
      </body>
    </html>
  );
}
